### ISSUE TITLE
Failed at the solid-ui@0.9.1 build-lib script 'babel src -d lib'.

### ISSUE THREAD

**Issue by Lerie82** [linkeddata/solid-ui#25]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle solid-ui@0.9.1~prebuild: solid-ui@0.9.1
6 silly lifecycle solid-ui@0.9.1~prebuild: no script for prebuild, continuing
7 info lifecycle solid-ui@0.9.1~build: solid-ui@0.9.1
8 verbose lifecycle solid-ui@0.9.1~build: unsafe-perm in lifecycle true
9 verbose lifecycle solid-ui@0.9.1~build: PATH: /usr/share/npm/bin/node-gyp-bin:/var/www/html/solid-ui/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
10 verbose lifecycle solid-ui@0.9.1~build: CWD: /var/www/html/solid-ui
11 silly lifecycle solid-ui@0.9.1~build: Args: [ '-c', 'npm run build-lib' ]
12 silly lifecycle solid-ui@0.9.1~build: Returned: code: 1  signal: null
13 info lifecycle solid-ui@0.9.1~build: Failed to exec build script
14 verbose stack Error: solid-ui@0.9.1 build: `npm run build-lib`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid solid-ui@0.9.1
16 verbose cwd /var/www/html/solid-ui
17 error Linux 3.18.0-16288-g64d05cf80004
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
19 error node v4.2.6
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error solid-ui@0.9.1 build: `npm run build-lib`
22 error Exit status 1
23 error Failed at the solid-ui@0.9.1 build script 'npm run build-lib'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the solid-ui package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run build-lib
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs solid-ui
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls solid-ui
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by melvincarvalho** [comment]
Works for me

babel src -d lib
src/acl-control.js -> lib/acl-control.js
src/acl.js -> lib/acl.js
src/create.js -> lib/create.js
src/iconBase.js -> lib/iconBase.js
src/index.js -> lib/index.js
src/log.js -> lib/log.js
src/matrix.js -> lib/matrix.js
src/media-capture.js -> lib/media-capture.js
src/messageArea.js -> lib/messageArea.js
src/ns.js -> lib/ns.js
src/pad.js -> lib/pad.js
src/preferences.js -> lib/preferences.js
src/signin.js -> lib/signin.js
src/store.js -> lib/store.js
src/table.js -> lib/table.js
src/tabs.js -> lib/tabs.js
src/test/test-matrix.js -> lib/test/test-matrix.js
src/test/test-tabs.js -> lib/test/test-tabs.js
src/utils.js -> lib/utils.js
src/widgets/dragAndDrop.js -> lib/widgets/dragAndDrop.js
src/widgets/error.js -> lib/widgets/error.js
src/widgets/index.js -> lib/widgets/index.js
src/widgets/peoplePicker.js -> lib/widgets/peoplePicker.js

------------

Perhaps try with a more recent version of npm / node?

**Comment by Lerie82** [comment]
$ npm -v
3.5.2

**Comment by melvincarvalho** [comment]
Mine : 

$ npm -v
5.3.0

The package [n](https://www.npmjs.com/package/n) might be a useful way to update various libraries.

**Comment by Lerie82** [comment]
I actually removed the .babelrc file and it worked!
